### ISSUE TITLE
Naming of “make-widget”

### ISSUE THREAD

**Issue by atroche** [arachne-framework/arachne-docs#9]
Hi!

In Stuart Sierra's [How To Name Clojure Functions] he [says](https://stuartsierra.com/2016/01/09/how-to-name-clojure-functions#orgheadline1):

“Pure functions which return values are named with nouns describing the value they return.

This is particularly good for constructors and accessors. No need to clutter up your function names with meaningless prefixes like get- and make-.”

But I can see arguments in favour of the `make-widget` style. What's your take on which is more idiomatic, @levand?

**Comment by levand** [comment]
So in general I do tend to agree with Stuart about naming things.

However, Arachne "constructor functions" are a pretty specific class of functions, and I've been playing around with naming questions to make them easily identifiable in code. Ideas include `make-foo`, `construct-foo` or `foo-ctor`. Or don't have unique names and just call out the fact that they're constructors in the docstr. 

I haven't settled on a preference yet. Apparently I was favoring `make-foo` at the time I wrote that tutorial :)

**Comment by atroche** [comment]
Cool, that makes sense. Thanks!
